CodeSystem: AicuraObservationCS
Id: aicura-observation
Title: "AICURA Observation CodeSystem"
Description: "AICURA custom observation codes for assessments, biomarkers, and imaging-derived measurements."
* ^url = "https://aicura-medical.com/fhir/coding/observation"
* ^version = "1.0"
* ^status = #active
* ^caseSensitive = true
* ^experimental = false
* ^content = #complete
* #"Global score [CDR]" "Global score [CDR]"
* #"Sum of Boxes [CDR]" "Sum of Boxes [CDR]"
* #"Total Score [NPI-Q]" "Total Score [NPI-Q]"
* #"Total Score [NPI-10]" "Total Score [NPI-10]"
* #"Total Score [ADASCog13]" "Total Score [ADASCog13]"
* #"Total Score [ADASCog13 NI]" "Total Score [ADASCog13 NI]"
* #"Total Score [ADCS-ADL-MCI]" "Total Score [ADCS-ADL-MCI]"
* #"Immediate Recall [Wechsler Scale revised]" "Immediate Recall [Wechsler Scale revised]"
* #"Delayed Recall [Wechsler Scale revised]" "Delayed Recall [Wechsler Scale revised]"
* #"Brain-Derived Neurotrophic Factor [BDNF]" "Brain-Derived Neurotrophic Factor [BDNF]"
* #"BDNF GG [Val/Val]" "BDNF GG [Val/Val]"
* #"BDNF GA [Val/Met]" "BDNF GA [Val/Met]"
* #"BDNF AA [Met/Met]" "BDNF AA [Met/Met]"
* #"MDS UPDRS Part I: Patient Questionnaire [Total Score]" "MDS UPDRS Part I: Patient Questionnaire [Total Score]"
* #"Repeatable Battery for the Assessment of Neuropsychological Status [RBANS]" "Repeatable Battery for the Assessment of Neuropsychological Status [RBANS]"
* #"RBANS A" "Baseline measurement [RBANS]"
* #"RBANS B" "Follow up measurement [RBANS]"
* #"RBANS C" "Longitudinal measurement 1 [RBANS]"
* #"RBANS D" "Longitudinal measurement 2 [RBANS]"
* #"Delayed Memory Index Score [RBANS-A]" "Delayed Memory Index Score [RBANS-A]"
* #"MRI Derived Volume Measurement" "MRI Derived Volume Measurement"
* #"MRI Derived Cortical Thickness Measurement" "MRI Derived Cortical Thickness Measurement"
* #"MRI Derived Surface Area Measurement" "MRI Derived Surface Area Measurement"
* #"PET Amyloid Measurement" "PET Amyloid Measurement"
* #"PET Amyloid SUVr Measurement" "PET Amyloid SUVr Measurement"
* #"PET Amyloid Harmonized SUVr Measurement" "PET Amyloid Harmonized SUVr Measurement"
* #"PET Amyloid Centiloid Measurement" "PET Amyloid Centiloid Measurement"
* #"PET Tau Measurement" "PET Tau Measurement"
* #"PET Tau SUVr Measurement" "PET Tau SUVr Measurement"
* #"Number of Microhaemorrhages" "Number of Microhaemorrhages"
* #"Growth associated protein 43 [GAP-43] (CSF)" "Growth associated protein 43 [GAP-43] (CSF)"
* #"Neurogranin (CSF) [Mass/Vol]" "Neurogranin (CSF) [Mass/Vol]"
* #"sTREM2 (CSF) [Mass/Vol]" "sTREM2 (CSF) [Mass/Vol]"
* #"sTREM2-HAASS (CSF) [Mass/Vol]" "sTREM2-HAASS (CSF) [Mass/Vol]"
* #"sTREM2-WASHU (CSF) [Mass/Vol]" "sTREM2-WASHU (CSF) [Mass/Vol]"
* #"Plasma P-tau181" "Plasma P-tau181"
* #"Tau protein.phosphorylated 217 [Mass/volume] in Serum or Plasma by mass-spectrometry" "Tau protein.phosphorylated 217 [Mass/volume] in Serum or Plasma by mass-spectrometry"
* #"Years Since First AD Symptoms" "Years Since First AD Symptoms"
* #SRDC "Sporadic Parkison's Disease"
