ValueSet: AicuraObservationCodeVS
Id: aicura-observation-code
Title: "AICURA Observation Code ValueSet"
Description: "Observation codes used in AICURA studies, including assessments, laboratory tests, genetics, vital signs, and imaging-derived measurements."
* ^experimental = false
// All AICURA custom observation codes
* include codes from system AicuraObservationCS
// SNOMED-CT codes (3)
* $SCT#273499007 "Hachinski ischemia score (assessment scale)"
* $SCT#415238003 "Rapid eye movement sleep behavior disorder (disorder)"
* $SCT#83156004 "Sense of smell impaired (finding)"
// LOINC codes (170)
* $LOINC#72106-8 "Total score [MMSE]"
* $LOINC#72172-0 "Total score [MoCA]"
* $LOINC#48545-8 "Geriatric depression scale (GDS) short version total"
* $LOINC#42315-2 "APOE gene Alleles E2 and E3 and E4, Blood or tissue specimen"
* $LOINC#77714-4 "Modified Hoen and Yahr stage [UPDRS]"
* $LOINC#77718-5 "MDS UPDRS Part I: Non-Motor Aspects of Experiences of Daily Living (nM-EDL) [Total Score]"
* $LOINC#77719-3 "MDS UPDRS Part II: Motor Aspects of Experiences of Daily Living (M-EDL) [Total Score]"
* $LOINC#77720-1 "MDS UPDRS Part III: Motor Examination [Total Score]"
* $LOINC#77721-9 "MDS UPDRS Part IV: Motor Complications [Total Score]"
* $LOINC#82590-1 "Years of education [#] - Reported"
* $LOINC#29463-7 "Body weight"
* $LOINC#8302-2 "Body height"
* $LOINC#39156-5 "Body mass index (BMI) [Ratio]"
* $LOINC#8310-5 "Body temperature"
* $LOINC#8462-4 "Diastolic blood pressure"
* $LOINC#8480-6 "Systolic blood pressure"
* $LOINC#8867-4 "Heart rate"
* $LOINC#9279-1 "Respiratory rate"
* $LOINC#33203-1 "Amyloid beta 42 peptide (CSF) [Mass/Vol]"
* $LOINC#70072-4 "Amyloid beta 40 peptide (CSF) [Mass/Vol]"
* $LOINC#33200-7 "Amyloid beta 42 peptide [Mass/volume] in Plasma"
* $LOINC#70073-2 "Amyloid beta 40 peptide [Mass/volume] in Plasma"
* $LOINC#30160-6 "Tau protein (CSF) [Mass/Vol]"
* $LOINC#72260-3 "Phosphorylated tau 181 IA (CSF) [Mass/Vol]"
* $LOINC#103675-5 "Phosphorylated tau 181 [Mass/volume] in Plasma by Immunoassay"
* $LOINC#104663-0 "Tau protein.phosphorylated 217 [Mass/volume] in Serum or Plasma by Immunoassay"
* $LOINC#100996-8 "Neurofilament light chain (CSF) [Mass/Vol]"
* $LOINC#101281-4 "Neurofilament light chain IA [Mass/Vol]"
* $LOINC#97604-3 "Glial fibrillary acidic protein [Mass/volume] in Plasma by Immunoassay"
* $LOINC#21738-0 "SNCA gene mutations tested for Molgen Nom (Bld/Tiss)"
* $LOINC#46988-2 "GBA gene mutations tested for Molgen Nom (Bld/Tiss)"
* $LOINC#47968-3 "PINK1 gene targeted mutation analysis Molgen Nom (Bld/Tiss)"
* $LOINC#53876-9 "LRRK2 gene targeted mutation analysis Molgen Nom (Bld/Tiss)"
* $LOINC#41071-2 "PARK2 gene targeted mutation analysis Molgen Nom (Bld/Tiss)"
* $LOINC#LA21356-3 "APOE e2/e2"
* $LOINC#LA21357-1 "APOE e2/e3"
* $LOINC#LA21358-9 "APOE e3/e3 (wild type)"
* $LOINC#LA21359-7 "APOE e3/e4"
* $LOINC#LA21360-5 "APOE e4/e4"
* $LOINC#LA21361-3 "APOE e2/e4"
* $LOINC#718-7 "Hemoglobin [Mass/volume] in Blood"
* $LOINC#4544-3 "Hematocrit [Volume Fraction] of Blood by Automated count"
* $LOINC#787-2 "MCV [Entitic mean volume] in Red Blood Cells by Automated count"
* $LOINC#785-6 "MCH [Entitic mass] by Automated count"
* $LOINC#786-4 "MCHC [Entitic Mass/volume] in Red Blood Cells by Automated count"
* $LOINC#788-0 "Erythrocyte [DistWidth] in Red Blood Cells by Automated count"
* $LOINC#26515-7 "Platelets [#/volume] in Blood"
* $LOINC#6690-2 "Leukocytes [#/volume] in Blood by Automated count"
* $LOINC#751-8 "Neutrophils [#/volume] in Blood by Automated count"
* $LOINC#26511-6 "Neutrophils/Leukocytes in Blood"
* $LOINC#731-0 "Lymphocytes [#/volume] in Blood by Automated count"
* $LOINC#26478-8 "Lymphocytes/Leukocytes in Blood"
* $LOINC#742-7 "Monocytes [#/volume] in Blood by Automated count"
* $LOINC#5905-5 "Monocytes/Leukocytes in Blood by Automated count"
* $LOINC#711-2 "Eosinophils [#/volume] in Blood by Automated count"
* $LOINC#713-8 "Eosinophils/Leukocytes in Blood by Automated count"
* $LOINC#704-7 "Basophils [#/volume] in Blood by Automated count"
* $LOINC#706-2 "Basophils/Leukocytes in Blood by Automated count"
* $LOINC#708-8 "Blasts [#/volume] in Blood by Manual count"
* $LOINC#26446-5 "Blasts/Leukocytes in Blood"
* $LOINC#748-4 "Myelocytes [#/volume] in Blood by Manual count"
* $LOINC#26498-6 "Myelocytes/Leukocytes in Blood"
* $LOINC#28541-1 "Metamyelocytes/Leukocytes in Blood"
* $LOINC#40651-2 "Metamyelocytes [Presence] in Blood"
* $LOINC#734-4 "Variant lymphocytes [#/volume] in Blood by Manual count"
* $LOINC#42250-1 "Variant lymphocytes/Leukocytes in Blood by Automated count"
* $LOINC#30229-9 "Band form neutrophils [#/volume] in Blood by Automated count"
* $LOINC#35332-6 "Band form neutrophils/Leukocytes in Blood by Automated count"
* $LOINC#30411-3 "Leukocytes Left Shift [Presence] in Blood"
* $LOINC#702-1 "Anisocytosis [Presence] in Blood by Light microscopy"
* $LOINC#10378-8 "Polychromasia [Presence] in Blood by Light microscopy"
* $LOINC#779-9 "Poikilocytosis [Presence] in Blood by Light microscopy"
* $LOINC#738-5 "Macrocytes [Presence] in Blood by Light microscopy"
* $LOINC#741-9 "Microcytes [Presence] in Blood by Light microscopy"
* $LOINC#728-6 "Hypochromia [Presence] in Blood by Light microscopy"
* $LOINC#802-9 "Spherocytes [Presence] in Blood by Light microscopy"
* $LOINC#10381-2 "Target cells [Presence] in Blood by Light microscopy"
* $LOINC#774-0 "Ovalocytes [Presence] in Blood by Light microscopy"
* $LOINC#11274-8 "Elliptocytes [Presence] in Blood by Light microscopy"
* $LOINC#7789-1 "Acanthocytes [Presence] in Blood by Light microscopy"
* $LOINC#7790-9 "Burr cells [Presence] in Blood by Light microscopy"
* $LOINC#7791-7 "Dacrocytes [Presence] in Blood by Light microscopy"
* $LOINC#38910-6 "Schistocytes [Presence] in Blood by Automated count"
* $LOINC#703-9 "Basophilic stippling [Presence] in Blood by Light microscopy"
* $LOINC#5908-9 "Giant platelets [Presence] in Blood by Light microscopy"
* $LOINC#32146-3 "Platelets Large [Presence] in Blood by Light microscopy"
* $LOINC#7798-2 "Smudge cells [Presence] in Blood by Light microscopy"
* $LOINC#11273-0 "Erythrocytes [Morphology] in Blood by Automated count"
* $LOINC#5902-2 "Prothrombin time (PT)"
* $LOINC#6301-6 "INR in Platelet poor plasma by Coagulation assay"
* $LOINC#2345-7 "Glucose [Mass/volume] in Serum or Plasma"
* $LOINC#17856-6 "Hemoglobin A1c/Hemoglobin.total in Blood by HPLC"
* $LOINC#17861-6 "Calcium [Mass/volume] in Serum or Plasma"
* $LOINC#35221-1 "Phosphate [Mass or Moles/volume] in Serum or Plasma"
* $LOINC#1742-6 "Alanine aminotransferase [Enzymatic activity/volume] in Serum or Plasma"
* $LOINC#1920-8 "Aspartate aminotransferase [Enzymatic activity/volume] in Serum or Plasma"
* $LOINC#2324-2 "Gamma glutamyl transferase [Enzymatic activity/volume] in Serum or Plasma"
* $LOINC#1777-2 "Alkaline phosphatase.bone [Enzymatic activity/volume] in Serum or Plasma"
* $LOINC#1975-2 "Bilirubin.total [Mass/volume] in Serum or Plasma"
* $LOINC#1968-7 "Bilirubin.direct [Mass/volume] in Serum or Plasma"
* $LOINC#1751-7 "Albumin [Mass/volume] in Serum or Plasma"
* $LOINC#2885-2 "Protein [Mass/volume] in Serum or Plasma"
* $LOINC#2160-0 "Creatinine [Mass/volume] in Serum or Plasma"
* $LOINC#3094-0 "Urea nitrogen [Mass/volume] in Serum or Plasma"
* $LOINC#3084-1 "Urate [Mass/volume] in Serum or Plasma"
* $LOINC#42570-2 "Sodium [Mass or Moles/volume] in Serum or Plasma"
* $LOINC#2823-3 "Potassium [Moles/volume] in Serum or Plasma"
* $LOINC#2075-0 "Chloride [Moles/volume] in Serum or Plasma"
* $LOINC#1963-8 "Bicarbonate [Moles/volume] in Serum or Plasma"
* $LOINC#2532-0 "Lactate dehydrogenase [Enzymatic activity/volume] in Serum or Plasma"
* $LOINC#2880-3 "Protein [Mass/volume] in Cerebral spinal fluid"
* $LOINC#7918-6 "HIV 1+2 Ab [Presence] in Serum"
* $LOINC#16933-4 "Hepatitis B virus core Ab [Presence] in Serum"
* $LOINC#22322-2 "Hepatitis B virus surface Ab [Presence] in Serum"
* $LOINC#5195-3 "Hepatitis B virus surface Ag [Presence] in Serum"
* $LOINC#5198-7 "Hepatitis C virus Ab [Units/volume] in Serum by Immunoassay"
* $LOINC#24011-9 "Hepatitis C virus Ab band pattern [Interpretation] in Serum by Immunoblot"
* $LOINC#2110-5 "Choriogonadotropin.beta subunit [Presence] in Serum or Plasma"
* $LOINC#2112-1 "Choriogonadotropin.beta subunit [Presence] in Urine"
* $LOINC#5778-6 "Color of Urine"
* $LOINC#5803-2 "pH of Urine by Test strip"
* $LOINC#53326-5 "Specific gravity of Urine by Automated test strip"
* $LOINC#5804-0 "Protein [Mass/volume] in Urine by Test strip"
* $LOINC#20406-5 "Deprecated Glucose [Mass/volume] in Urine by Test strip"
* $LOINC#50558-6 "Nitrite [Presence] in Urine by Automated test strip"
* $LOINC#20409-9 "Erythrocytes [#/volume] in Urine by Test strip"
* $LOINC#5821-4 "Leukocytes [#/area] in Urine sediment by Microscopy high power field"
* $LOINC#13945-1 "Erythrocytes [#/area] in Urine sediment by Microscopy high power field"
* $LOINC#12235-8 "Microscopic observation [Identifier] in Urine sediment by Light microscopy"
* $LOINC#20453-7 "Epithelial cells [Presence] in Urine sediment by Light microscopy"
* $LOINC#12248-1 "Epithelial cells.renal [Presence] in Urine sediment by Light microscopy"
* $LOINC#8249-5 "Transitional cells [Presence] in Urine sediment by Light microscopy"
* $LOINC#25162-9 "Hyaline casts [Presence] in Urine sediment by Light microscopy"
* $LOINC#25160-3 "Granular casts [Presence] in Urine sediment by Light microscopy"
* $LOINC#33825-1 "WBC casts [Presence] in Urine sediment by Light microscopy"
* $LOINC#33804-6 "RBC casts [Presence] in Urine sediment by Light microscopy"
* $LOINC#33862-4 "Waxy casts [Presence] in Urine sediment by Light microscopy"
* $LOINC#34173-5 "Mixed cellular casts [Presence] in Urine sediment by Light microscopy"
* $LOINC#25145-4 "Bacteria [Presence] in Urine sediment by Light microscopy"
* $LOINC#32356-8 "Yeast [Presence] in Urine sediment by Light microscopy"
* $LOINC#5774-5 "Calcium oxalate crystals [Presence] in Urine sediment by Light microscopy"
* $LOINC#5814-9 "Triple phosphate crystals [Presence] in Urine sediment by Light microscopy"
* $LOINC#5766-1 "Ammonium urate crystals [Presence] in Urine sediment by Light microscopy"
* $LOINC#12453-7 "Phosphate crystals amorphous [Presence] in Urine sediment by Light microscopy"
* $LOINC#12454-5 "Urate crystals amorphous [Presence] in Urine sediment by Light microscopy"
* $LOINC#5773-7 "Calcium carbonate crystals [Presence] in Urine sediment by Light microscopy"
* $LOINC#5784-4 "Cystine crystals [Presence] in Urine sediment by Light microscopy"
* $LOINC#5812-3 "Sulfonamide crystals [Presence] in Urine sediment by Light microscopy"
* $LOINC#60340-7 "Crystals.amorphous [Presence] in Urine sediment by Light microscopy"
* $LOINC#33861-6 "Starch granules [Presence] in Urine sediment by Light microscopy"
* $LOINC#19261-7 "Amphetamines [Presence] in Urine by Screen method"
* $LOINC#105967-4 "Amphetamine [Presence] in Urine"
* $LOINC#3779-6 "Methamphetamine [Presence] in Urine"
* $LOINC#14267-9 "Methylenedioxymethamphetamine [Presence] in Urine"
* $LOINC#19270-8 "Barbiturates [Presence] in Urine by Screen method"
* $LOINC#3377-9 "Barbiturates [Presence] in Urine"
* $LOINC#14316-4 "Benzodiazepines [Presence] in Urine by Screen method"
* $LOINC#3390-2 "Benzodiazepines [Presence] in Urine"
* $LOINC#18282-4 "Cannabinoids [Presence] in Urine by Screen method"
* $LOINC#3427-2 "Cannabinoids [Presence] in Urine"
* $LOINC#14314-9 "Benzoylecgonine [Presence] in Urine by Screen method"
* $LOINC#3397-7 "Cocaine [Presence] in Urine"
* $LOINC#3773-9 "Methadone [Presence] in Urine"
* $LOINC#42252-7 "Methaqualone+Metabolite [Presence] in Urine by Screen method"
* $LOINC#3879-4 "Opiates [Presence] in Urine"
* $LOINC#10998-3 "oxyCODONE [Presence] in Urine"
* $LOINC#19659-2 "Phencyclidine [Presence] in Urine by Screen method"
* $LOINC#3936-2 "Phencyclidine [Presence] in Urine"
* $LOINC#59960-5 "Propoxyphene [Moles/volume] in Urine"
* $LOINC#42242-8 "Ethanol [Presence] in Urine by Screen method"
